### ISSUE TITLE
Coloured Vote Yes for Me badge still incorrect

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#25]
If you look at it on a dark background, you can see a white line through "Me"

Let me know if I need to send more artwork.

**Comment by Ankhwatcher** [comment]
Addressed in https://github.com/HackForEquality/android-app/commit/5389a8459413a132526230f9e782a1ea09fad7fb and https://github.com/HackForEquality/android-app/commit/62896fb8f890f66f37428d39355ff8189d30a82a.
New badges have now been inserted at the various densities.

**Comment by canuckjacq** [comment]
This is still incorrect. I'll have a look at the images I have.
